import { Container } from "@mantine/core";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";

const LoginPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dogewatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>login here</Container>
    </>
  );
};

export default LoginPage;
